name: Build Swiss-Eph WASM

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Emscripten SDK
        run: |
          git clone https://github.com/emscripten-core/emsdk.git emsdk
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh

      - name: Clone Swiss Ephemeris C source
        run: |
          git clone https://github.com/aloistr/swisseph.git swisseph

      - name: Build Swiss-Eph to WASM
        run: |
          cd swisseph
          emcc -std=c99 -O3 -s STANDALONE_WASM \
               -s EXPORTED_FUNCTIONS='["_swe_julday","_swe_calc_ut","_swe_set_ephe_path"]' \
               -s EXTRA_EXPORTED_RUNTIME_METHODS='["cwrap","ccall"]' \
               *.c \
               -o swe_wasm.js

      - name: Move artifacts into repo
        run: |
          mkdir -p lib/swiss-ephem
          mv swisseph/swe_wasm.js lib/swiss-ephem/
          mv swisseph/swe_wasm.wasm lib/swiss-ephem/

      - name: Commit & push WASM files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update Swiss-Eph WASM build"
          file_pattern: "lib/swiss-ephem/*"
